"""Smoke test for gprism.model.em on the synthetic fixture."""

import numpy as np
import pytest

torch = pytest.importorskip("torch")

from gprism.config import GPRISMConfig
from gprism.model.em import run_em


def test_run_em_recovers_two_person_mixture(tiny_mpileup_path):
    """EM should recover the (0.7, 0.3) mixture proportions within ~0.08.

    The fixture is a deterministic 400-site synthetic mixture generated by
    conftest.py with a_vec=(0.7, 0.3), depth=200.
    """
    torch.manual_seed(0)
    np.random.seed(0)

    config = GPRISMConfig(
        phi=200.0, max_k=2, n_init=1, max_em_iter=300, min_depth=10,
    )
    # Try up to 5 random starts to avoid flakiness from bad initialisations
    best = None
    for _ in range(5):
        result = run_em(tiny_mpileup_path, K=2, config=config)
        if result is None:
            continue
        if best is None or result["bic"] < best["bic"]:
            best = result

    assert best is not None
    a = sorted(best["a_vec"].tolist(), reverse=True)
    # The major contributor should be recovered close to 0.7
    assert a[0] == pytest.approx(0.7, abs=0.08)
    assert a[1] == pytest.approx(0.3, abs=0.08)
    assert np.isfinite(best["bic"])
    assert np.isfinite(best["loglike"])
